/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_pagos;

import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import sis_pagos.Interfaz;

/**
 *
 * @author georg
 */
public class VentanaAcceso extends javax.swing.JFrame {

    String usuario, contraseña;

    /**
     * Creates new form VentanaAcceso
     */
    public VentanaAcceso() {
        initComponents();
        btnacceder.setVisible(true);
        this.setSize(400, 400);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        btnacceder = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(35, 90, 110, 38);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Contraseña:  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 170, 38);

        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtusuario);
        txtusuario.setBounds(200, 80, 140, 30);

        txtcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(txtcontraseña);
        txtcontraseña.setBounds(200, 120, 140, 30);

        btnacceder.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        btnacceder.setForeground(new java.awt.Color(51, 0, 51));
        btnacceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/pasar-al-siguiente (Copiar).png"))); // NOI18N
        btnacceder.setText("Acceder");
        btnacceder.setContentAreaFilled(false);
        btnacceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnacceder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnacceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccederActionPerformed(evt);
            }
        });
        btnacceder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnaccederKeyPressed(evt);
            }
        });
        getContentPane().add(btnacceder);
        btnacceder.setBounds(20, 190, 160, 130);

        mensaje.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(mensaje);
        mensaje.setBounds(190, 200, 160, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccederActionPerformed
        boolean band = false;
        usuario = txtusuario.getText();
        contraseña = txtcontraseña.getText();
        Interfaz abrir = new Interfaz();
        if (usuario.isEmpty() || contraseña.isEmpty()) {
            mensaje.setText("necesitas llenar el campo");
        } else {
            abrir.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaccederActionPerformed

    private void btnaccederKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnaccederKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnaccederKeyPressed

    private void txtcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraseñaKeyPressed
        boolean band = false;
        if ((evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER)) {
            usuario = txtusuario.getText();
            contraseña = txtcontraseña.getText();
            Interfaz abrir = new Interfaz();
            if (usuario.isEmpty() || contraseña.isEmpty()) {
                mensaje.setText("necesitas llenar el campo");
            } else {

                abrir.setVisible(true);
                this.setVisible(false);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaKeyPressed

    private void txtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyPressed
        boolean band = false;
        if ((evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER)) {
            usuario = txtusuario.getText();
            contraseña = txtcontraseña.getText();
            Interfaz abrir = new Interfaz();
            if (usuario.isEmpty() || contraseña.isEmpty()) {
                mensaje.setText("necesitas llenar el campo");
            } else {

                abrir.setVisible(true);
                this.setVisible(false);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
